### PR TITLE
Add flag to create copy-in destination dirs

### PR DESCRIPTION
**Pull request by grembo**
If set, this creates $(dirname "$destdir"). Addresses #172.

Implementation is conservative in that it executes `mkdir` inside the pot.

Example of use:

    pot copy-in -p dnspot -s dns.d/dns.conf -cd /usr/local/etc/.
    pot copy-in -p dnspot -s dns.d/some.txt -cd /usr/local/share/some/test.txt

This also fixes a bug in _make_temp_source() which broke copy-in
functionality.

### CODE REVIEW

**Comment by pizzamig** [comment]
Thanks for the implementation! It looks good to me,
It would be great if, in the PR, you can also modify the CHANGELOG.md, in the section `Added`

**Comment by grembo** [comment]
Used #172 in changelog (original feature request), not pull request ID:

    - copy-in: -c option to create missing dirs on copy-in (#172)

I this preferred (seemed more reasonable)?

**Comment by urosgruber** [comment]
Could the flag be ON by default? Unless this would brake compatibility with older versions.

With my experience I always need to create folders first.

**Comment by grembo** [comment]
@pizzamig Merge is looking good here

@urosgruber I would keep it like it is at this point, as it mimics familiar "mkdir" behavior (+ keeping it backwards compatible helps with POLA). Since creating a flavor now actually fails if the command file doesn't execute cleanly, it has the additional advantage of catching typos early (e.g., if you write _/ect/resolve.conf_ in your copy-in, you probably want this to fail early instead of creating _/ect_ for you).

**Pull request merged**
